@host=http://localhost:8000

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Tester",
    "email": "david@test.com",
    "password": "Password1!"
}